### ISSUE TITLE
Version 1.3 requires PHP 5.5 but the Vagrant box has PHP 5.4.43

### ISSUE THREAD

**Issue by TomHAnderson** [zfcampus/zf-apigility-skeleton#103]
The Vagrant install does not install PHP 5.5 so you cannot compose your vendors from within the Vagrant box.

```sh
vagrant@precise64:/vagrant$ ./composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php >=5.5 but your PHP version (5.4.43-1+deb.sury.org~precise+1) does not satisfy that requirement.
```

**Comment by TomHAnderson** [comment]
Blocks https://github.com/TomHAnderson/zf-oauth2-doctrine/pull/41

**Comment by weierophinney** [comment]
On investigation, I think we need to use a different base box. Will look into it soon.

**Comment by weierophinney** [comment]
@TomHAnderson I'm having trouble getting things updated; I have an updated box, which brings updated PHP, and I've ensured the config files are being properly placed, but the server is responding with a 403 on all requests. It may be a day or two before I have this ready.

In the meantime, the Docker configuration works great, and you can use that as an alternative.

**Comment by TomHAnderson** [comment]
Is php cgi w/ no Authorization header?  Thanks for working on this.

**Comment by jeremiahsmall** [comment]
We could consider getting rid of the puppet provisioner, and use a stand-alone `Vagrantfile` like this one. https://github.com/zendframework/ZendSkeletonApplication/blob/master/Vagrantfile

**Comment by TomHAnderson** [comment]
Having a MySQL install in the virtual machine is very useful.

**Comment by weierophinney** [comment]
@jeremiahsmall I considered it, but that provisioner was one I wrote as my first foray into Vagrant, and it's not terribly robust.

I've generated new configuration using PuPHPet (which was the basis of our original configuration for the Apigility skeleton), and have opened #105 with the patch. The initial `vagrant up` takes a while to provision, but after that, it's very fast, and "just works". You also end up with a lot of tools out-of-the-box, which I think will be useful for a base box.

**Comment by jeremiahsmall** [comment]
@weierophinney, oh, I didn't realize that. I though @gianarb had written that one. It was fairly recently PR'd by him: https://github.com/zendframework/ZendSkeletonApplication/pull/288

In any case, we also use Puppet provisioners, but we have managed to keep most of the mess out of the repo by gitignoring `.puppet/modules`
