### ISSUE TITLE
Problem with DB Connected creation on 1.3.1

### ISSUE THREAD

**Issue by g3luka** [zfcampus/zf-apigility-skeleton#107]
Infinite loading and the files are not generated.
The Chrome console displays the following error: "... 'table_name' of undefined."

**Comment by g3luka** [comment]
In version 1.3.0 works correctly.

**Comment by sschueller** [comment]
I can confirm. (dev-master master 4. August)

To reproduce:
1. new install
2. add db connection
3. create new api
4. create new service with db connection
5. select table and click "create service"

Full chrome output:
{code}
TypeError: Cannot read property 'table_name' of undefined
    at a.e.ok (c22d22af.apigility.js:1)
    at 6a8334db.vendor.js:6
    at e (6a8334db.vendor.js:6)
    at k.$eval (6a8334db.vendor.js:5)
    at k.$apply (6a8334db.vendor.js:5)
    at HTMLButtonElement.<anonymous> (6a8334db.vendor.js:6)
    at HTMLButtonElement._.event.dispatch (6a8334db.vendor.js:2)
    at HTMLButtonElement.q.handle (6a8334db.vendor.js:2)
{code}

**Comment by alessandrogarcez** [comment]
Hi @g3luka, I had the same problem. Take a look please.

https://github.com/zfcampus/zf-apigility-admin/issues/307

http://stackoverflow.com/questions/31839293/error-while-generating-a-new-service-using-db-connect-in-apigility

**Comment by diogoazevedos** [comment]
Same problem, any solution?

**Comment by PipStyles** [comment]
I can confirm this is STILL an issue and has broken Apigility Admin for creating DB-Connected REST services at this time. Completely fresh installs using:

    git clone https://github.com/zfcampus/zf-apigility-skeleton.git

or

    curl -s https://getcomposer.org/installer | php --

or

    download zip/tar from https://github.com/zfcampus/zf-apigility-skeleton/releases

followed by (command) if needed

    composer install

ALL of the above yield:

    TypeError: Cannot read property 'table_name' of undefined
    at a.e.ok (http://localhost/myapp/public/apigility-ui/c22d22af.apigility.js:1:6663)
    *snip*

in javascript console. This is installing per instructions in zf-apigility-skeleton and/or installing the skeleton instead.

**Comment by migmolrod** [comment]
In my case, I get a different console error: ```Error: e.rest is undefined```

I can add the API. I can add the database adapter. I can even start to create a DB connected service (Apigility is able to correctly detect all the MySQL tables). But if I select one and click "Create service"... infinite loading + 'e.rest is undefined' error.

Am I the only one?

**Comment by shaunj** [comment]
I am getting the same error as @migmolrod 
![capture](https://cloud.githubusercontent.com/assets/1225533/11069738/58a4a754-879d-11e5-9f38-94a65487230e.PNG)

**Comment by shaunj** [comment]
I replaced the js file in my project located at zfcampus\zf-apigility-admin-ui\dist\apigility-ui\c22d22af.apigility.js that was downloaded via composer with the file at https://github.com/zfcampus/zf-apigility-admin-ui/blob/1daff7ab993e8093ab831975f35cf3eda7ba9725/dist/apigility-ui/c22d22af.apigility.js and it worked just fine. Not sure why the latest wasn't download loaded when using the following

"require" : {
    "php" : ">=5.5",
    "zendframework/zendframework" : "2.5.0",
    "zfcampus/zf-apigility" : "1.2.1",
    "zfcampus/zf-apigility-documentation" : "1.1.0",
    "zfcampus/zf-development-mode" : "2.1.1"
  },
  "require-dev" : {
    "zendframework/zftool" : "dev-master",
    "zendframework/zend-developer-tools" : "dev-master",
    "zfcampus/zf-apigility-admin" : "1.3.2",
    "zfcampus/zf-deploy" : "1.1.0",
    "zfr/zfr-cors" : "v1.2.0",
    "zend/zend-studio-development-mode" : "1.0.1"
  },

**Comment by migmolrod** [comment]
Wow. Will give it a try, for sure. I pretty much gave up with that problem.
Thanks shaunj.

**Comment by shaunj** [comment]
Hope it helps @migmolrod.

**Comment by shaunj** [comment]
@migmolrod I may have spoken too soon. I tried to create another new service and it didn't work. It worked to create one new service checking to see if I changed anything else. Still investigating.

**Comment by tushariscoolster** [comment]
@shaunj  @migmolrod  Fixes https://github.com/tushariscoolster/apigility-db-connected-fix

**Comment by aiamk** [comment]
@shaunj @migmolrod same issue.

@tushariscoolster i tried your repository still the same issue, can you explain how to fix it?

**Comment by tushariscoolster** [comment]
@aiamk impossible, i already fixed it, i used this repo multiple times

**Comment by aiamk** [comment]
@tushariscoolster can you explain how to fix it manually? if you don't mind? or which files i have to replace?

**Comment by tushariscoolster** [comment]
@aiamk give me a day, am travelling, will let u know the steps.

**Comment by aiamk** [comment]
@tushariscoolster Thank you for your response, I found the solution: https://github.com/zfcampus/zf-apigility-admin-ui/issues/74

**Comment by tushariscoolster** [comment]
@aiamk  Cool
