### ISSUE TITLE
Can't composer update!

### ISSUE THREAD

**Issue by aaronweatherall** [zfcampus/zf-apigility-skeleton#125]
Hey team,

If you do a composer update on the skeleton, Apigility won't work anymore.

The requirements for `"zendframework/zendframework": "^2.5.3",` are satisfiable by 2.7.6 which installs zendframework/zend-servicemanger:2.7.6. This version doesn't have the `FactoryInterface` in the right location. It seems to be rectified in 3.0, but I'm not sure if apigility is ready for that.

When you composer install zfcampus/zf-api-problem on its own, it installs ZF3 which has fixed this issue. I guess you wouldn't pick it up if you're just running tests against that repo on its on.

I'm happy to submit a pull request, but it'll be broken if the requirement changes to ZF3.

Reason: I'm trying to keep apigility up to date, and the composer requirements are too flexible if there are compatbility issues. Either the skeleton needs to be locked to specific versions, or at least have less flexible requirement tags.

Thanks guys!

**Comment by aaronweatherall** [comment]
I note this repo has version 3.1.0 preinstalled, but composer update actually downgrades a bunch of dependancies due to its < 3.0 requirement.

**Comment by Iraecio** [comment]
same proble now my api broken in api-problem
`Fatal error: Interface 'Zend\ServiceManager\Factory\FactoryInterface' not found in F:\PROJETOS\Api\vendor\zfcampus\zf-api-problem\src\Factory\ApiProblemListenerFactory.php on line 14`

**Comment by Ben85** [comment]
make a fresh install via:
`curl -sS https://apigility.org/install | php`
and
`composer update`
open the page in browser ends in:
`Fatal error: Uncaught Error: Class 'Zend\InputFiler\InputFilterAbstractServiceFactory' not found`
have I missed something? last week everything was fine.

**Comment by madalinignisca** [comment]
Seems like dependencies versions are not restrictive enough to make sure you don't get any new major version for some packages and the app breaks.

From my opinion when managing dependencies, we should allow updating only the minor versions, and release with major versions after more intense tests.

**Comment by madalinignisca** [comment]
A quick fix for who encounters the problem until another proper fix is coming in the needed component:

composer require "zfcampus/zf-apigility-admin-ui:~1.2"

This has worked for me, as it doesn't updated zend framework, it just makes sure that the admin-ui is pulled and the proper lock file is now refreshed and I can add other packages (like I'm following the tutorial and faced this exact issue)

**Comment by weierophinney** [comment]
If you update now, you should get a 1.5 series of zf-apigility-admin. This component now includes a migration script for updating your application to fully work with and adopt v3 components from Zend Framework. (In point of fact, the latest versions of all Apigility components all work with both v2 and v3 releases of ZF components; most of those updates came after the last comments to this issue, however.)

[Visit the documentation for more information on the migration tooling.](https://apigility.org/documentation/intro/updating-to-1-4)
