### ISSUE TITLE
Docker image build fails

### ISSUE THREAD

**Issue by burkl** [zfcampus/zf-apigility-skeleton#128]
As the latest Docker image php:5.6-apache (with PHP 5.6.23) doesn't provide the file /usr/src/php/php.ini-production anymore, the Apigility docker image build process fails. See https://github.com/docker-library/php/commit/f016f5dc420e7d360f7381eb014ac6697e247e11#diff-7da0c085907307a21df5836453180140 , the command ```docker-php-source delete``` has been added.

Quick fix: Change in the Dockerfile and Dockerfile-dev line
```FROM php:5.6-apache```
to
```FROM php:5.6.22-apache```
(you have to live with PHP 5.6.22 instead of PHP 5.6.23...)

Other solution would be to place the php.ini-production into the apigility repo and use this file for moving to the appropriate place in the docker image.

**Comment by newPOPE** [comment]
It seems that this issue is obsolete and can be closed. Master has `FROM php:7.0-apache` see https://github.com/zfcampus/zf-apigility-skeleton/blob/master/Dockerfile#L24
