### ISSUE TITLE
Error when updating, installing module, and upgrading.

### ISSUE THREAD

**Issue by viyirenov** [zfcampus/zf-apigility-skeleton#132]
I tried to use: `composer install doctrine/doctrine-orm-module` and I get an error:

````
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package zfcampus/zf-apigility-admin-ui (locked at 1.2.2, required as ^1.2.3) is satisfiable by zfcampus/zf-apigility-admin-ui[1.2.2] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Can only install one of: zendframework/zend-hydrator[1.1.0, 1.0.0].
    - Can only install one of: zendframework/zend-hydrator[1.1.0, 1.0.0].
    - Can only install one of: zendframework/zend-hydrator[1.1.0, 1.0.0].
    - doctrine/doctrine-orm-module 1.0.0 requires zendframework/zend-hydrator ^1.1 -> satisfiable by zendframework/zend-hydrator[1.1.0].
    - Installation request for doctrine/doctrine-orm-module ^1.0 -> satisfiable by doctrine/doctrine-orm-module[1.0.0].
    - Installation request for zendframework/zend-hydrator (locked at 1.0.0) -> satisfiable by zendframework/zend-hydrator[1.0.0].
```

If I try to update: `composer update`, error again:

````
Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message
'Module (AssetManager) could not be initialized.' in C:\apigility\vendor\zendframework\zend-
modulemanager\src\ModuleManager.php:203 Stack trace: #0 C:\apigility\vendor\zendframework\zend-
modulemanager\src\ModuleManager.php(175): Zend\ModuleManager\ModuleManager-
>loadModuleByName(Object(Zend\ModuleManager\ModuleEvent)) #1 
C:\apigility\vendor\zendframework\zend-modulemanager\src\ModuleManager.php(97): 
Zend\ModuleManager\ModuleManager->loadModule('AssetManager') #2 [internal function]: 
Zend\ModuleManager\ModuleManager-
>onLoadModules(Object(Zend\ModuleManager\ModuleEvent)) #3 
C:\apigility\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): 
call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent)) #4 
C:\apigility\vendor\zendframework\zend-eventmanager\src\EventManager.php(251): Zend\EventMa in 
C:\apigility\vendor\zendframework\zend-modulemanager\src\ModuleManager.php on line 203
```

If I try to solve the `AssetManager` removal with: `vendor/bin/apigility-upgrade-to-1.5.bat`, error again:

```
Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message
'Module (ZF\DevelopmentMode) could not be initialized.' in C:\apigility\vendor\zendframework\zend-
modulemanager\src\ModuleManager.php:203 Stack trace: #0 C:\apigility\vendor\zendframework\zend-
modulemanager\src\ModuleManager.php(175): Zend\ModuleManager\ModuleManager-
>loadModuleByName(Object(Zend\ModuleManager\ModuleEvent)) #1 
C:\apigility\vendor\zendframework\zend-modulemanager\src\ModuleManager.php(97): 
Zend\ModuleManager\ModuleManager->loadModule('ZF\\DevelopmentM...') #2 
C:\apigility\vendor\zendframework\zend-eventmanager\src\EventManager.php(271): 
Zend\ModuleManager\ModuleManager-
>onLoadModules(Object(Zend\ModuleManager\ModuleEvent)) #3 
C:\apigility\vendor\zendframework\zend-eventmanager\src\EventManager.php(143): 
Zend\EventManager\EventManager->triggerListeners(Object(Zend\ModuleManager\ModuleEven in 
C:\apigility\vendor\zendframework\zend-modulemanager\src\ModuleManager.php on line 203
```

edit:

I discovered what happened for the `DevelopmentMode` error. Before updating I used the zftool to create a module and it modified the `application.config.php` instead of the `modules.config.php`... After removing the `application.config.php` and renaming `application.config.php.old` to `application.config.php` I got new errors:

```
Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message
'Module (Zend\Hydrator) could not be initialized.' in C:\apigility\vendor\zendframework\zend-
modulemanager\src\ModuleManager.php:203 Stack trace: #0 
C:\apigility\vendor\zendframework\zend-modulemanager\src\ModuleManager.php(175): 
Zend\ModuleManager\ModuleManager-
>loadModuleByName(Object(Zend\ModuleManager\ModuleEvent)) #1 
C:\apigility\vendor\zendframework\zend-modulemanager\src\ModuleManager.php(97): 
Zend\ModuleManager\ModuleManager->loadModule('Zend\\Hydrator') #2 
C:\apigility\vendor\zendframework\zend-eventmanager\src\EventManager.php(271): 
Zend\ModuleManager\ModuleManager-
>onLoadModules(Object(Zend\ModuleManager\ModuleEvent)) #3 
C:\apigility\vendor\zendframework\zend-eventmanager\src\EventManager.php(143): 
Zend\EventManager\EventManager->triggerListeners(Object(Zend\ModuleManager\ModuleEvent)) #4 
C:\ in C:\apigility\vendor\zendframework\zend-modulemanager\src\ModuleManager.php on line 203
```

I'm kinda stuck, what can I do?

PHP: 5.6.24

**Comment by viyirenov** [comment]
I solved following this [manual ](https://github.com/zfcampus/zf-apigility-admin/blob/1.5.0/README.md#upgrading) instead of using the script.

**Comment by jguittard** [comment]
@viyirenov should be solved soon https://github.com/doctrine/DoctrineORMModule/pull/479

**Comment by jguittard** [comment]
Closing as it's related to https://github.com/doctrine/DoctrineORMModule dependencies

**Comment by viyirenov** [comment]
@jguittard I though I solved but it's not working when I try to access any route, this is what I get:

````
Fatal error: Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotFoundException' with 
message 'A plugin by the name "translate" was not found in the plugin manager 
Zend\View\HelperPluginManager' in C:\apigility\vendor\zendframework\zend-
servicemanager\src\AbstractPluginManager.php:133 Stack trace: #0 
C:\apigility\vendor\zendframework\zend-view\src\Renderer\PhpRenderer.php(373): 
Zend\ServiceManager\AbstractPluginManager->get('translate', NULL) #1 
C:\apigility\vendor\zendframework\zend-view\src\Renderer\PhpRenderer.php(391): 
Zend\View\Renderer\PhpRenderer->plugin('translate') #2 
C:\apigility\module\Application\view\error\index.phtml(1): Zend\View\Renderer\PhpRenderer-
>__call('translate', Array) #3 C:\apigility\module\Application\view\error\index.phtml(1): 
Zend\View\Renderer\PhpRenderer->translate('An error occurr...') #4 
C:\apigility\vendor\zendframework\zend-vie in C:\apigility\vendor\zendframework\zend-
servicemanager\src\AbstractPluginManager.php on line 133
```

The only problem is that I can't do anything to install doctrine cause of the updates they made on the modules and I have to finish a job for tomorrow, I'm kinda stuck with errors. :(

**Comment by jguittard** [comment]
It looks like there is a mess with your dependencies... 
About the **translate** plugin, you may resolve it by adding:
```shell
composer require zendframework/zend-mvc-i18n
```
in your composer file and:
```php
'modules' => [
    /** ... */
    'Zend\Mvc\I18n'
    /** ... */
],

As for Doctrine, there **are** solutions to make it work and compliant with ZF 3.0 packages. But it's in WIP for now. We are a few to work on it, should be available soon, but no release date. At least not tomorrow...

I'd suggest you either rollback to stable and compatible ZF 2.* packages, or dive into Doctrine config for your night...

Hope it helps (a bit)... Good luck anyway!

**Comment by viyirenov** [comment]
@jguittard 
I installed `composer require zendframework/zend-mvc-i18n`, updated the configuration file and the error doesn't go away:

> I'd suggest you either rollback to stable and compatible ZF 2.* packages, or dive into Doctrine config for your night...

I can't, if I install apigility and try to install the doctine I get an error saying: `Your requirements could not be resolved to an installable set of packages.` (the first error on this issue).

I can't require doctrine module, nor put it on my composer.json and try to update cause it will update to the latest apigility and all the other errors come with it.

I'm kinda stuck, I don't know how to solve that.

**Comment by viyirenov** [comment]
Yay, I solved the last error:

I had to delete the cache, use `composer require zendframework/zend-mvc-i18n`, and add this to my configuration file:

```
'modules' => [
     'Zend\I18n',
     'Zend\Mvc\I18n',
     // ...
],
```

**Comment by jguittard** [comment]
That's a start... 👍 
Now, do you intend to use `zf-apigilty-doctrine` or just `doctrineORMModule`?

**Comment by viyirenov** [comment]
I don't know how to use `zf-apigility-doctrine`, there are no documentation, at least I couldn't find anything helpful.
And now I can't install `doctrineORMModule` :-1: 
`Your requirements could not be resolved to an installable set of packages.`

Oh gosh...

@Ocramius @weierophinney @webimpress @jguittard

**Comment by webimpress** [comment]
@viyirenov `zf-apigility-doctrine` is not ready yet. I'm working on it in https://github.com/zfcampus/zf-apigility-doctrine/pull/267
Please be patient :)

**Comment by viyirenov** [comment]
Is there a way for me o rollback to apigility with ZF 2.* and install doctrine without getting errors?

**Comment by jguittard** [comment]
@viyirenov There **are** some documentation, even an implementation in the UI Admin I myself made :) 
I agree there is a lack of thorough documentation and/or (video) tutorials. But `zf-apigility-doctrine` basically *just* relies on your (existing) Doctrine configuration.

@webimpress thanks for taking care of it. I'm drowned with tons of work those last months. I'll review once you're done ;) 👍

**Comment by jguittard** [comment]
@viyirenov Of course there is, just stick with a 1.3.* version of the skeleton. And watch your constraint keys when you add dependencies (~, *, ^, ...) like Doctrine. It has a **huge** impact when you launch `composer update` ;)

**Comment by viyirenov** [comment]
@jguittard 

I tried to install the apigility 1.3.3 using:
`composer create-project -sdev zfcampus/zf-apigility-skeleton:^1.3.3`

and the doctrine orm module with:
`composer require doctrine/doctrine-orm-module:0.*`

And with no success, the error remains:

`The requested package zfcampus/zf-apigility-admin-ui (locked at 1.2.2, required as ^1.2.3) is satisfiable by zfcampus/zf-apigility-admin-ui[1.2.2] but these conflict with your requirements or minimum-stability.`

**Comment by jguittard** [comment]
@viyirenov do a simple `composer update` after installing the skeleton and before requiring doctrine-orm-module ;)

**Comment by viyirenov** [comment]
@jguittard Thank you very much, it's solved. I hope the new version come soon.

**Comment by viyirenov** [comment]
I did and it updated to the latest version of the apigility and again, the same errors.

**Comment by viyirenov** [comment]
Is there anyone to help me with that?

**Comment by jguittard** [comment]
I did install composer create-project -sdev zfcampus/zf-apigility-skeleton:^1.3.3 and a composer update and doctrine, everything went fine

**Comment by viyirenov** [comment]
@jguittard Have you tried to create the server `php -S 0.0.0.0:8080 -t public` and enter? It doesn't load the assets, that is what is wrong. Doctrine is installing, but I think that some module updated and now it doesn't work no matter the skeleton version.

**Comment by viyirenov** [comment]
I solved the problem and here is the steps:

1 - Install the apigility skeleton version 1.3.1:
`composer create-project -sdev zfcampus/zf-apigility-skeleton:^1.3.3`

2 - Update using composer (using `--lock` to make sure it won't update to the latest versions and mess everything up):
`composer update --lock`

3 - Put the doctrine requirement on your `composer.json`:
```
    "require": {
        // ....
        "doctrine/doctrine-orm-module": "0.*"
    },
```

4 - Update using composer again in order to add the doctrine to the vendor folder - and to the lock file as well:
`composer update --lock`

I hope it helps someone.
