### ISSUE TITLE
When using Docker, apache webroot still default

### ISSUE THREAD

**Issue by back-2-95** [zfcampus/zf-apigility-skeleton#139]
I created container just fine, but when accessing http://localhost:8080/ I just get "This site can’t be reached".

When I go to container and check apache configuration, webroot still points to `/var/www/html`instead of `/var/www/public`

Others getting the same?

I'm using latest Docker 1.12 on OSX El Capitan.

**Comment by back-2-95** [comment]
PR #138 will fix this issue.

**Comment by weierophinney** [comment]
Fixed with #138
