### ISSUE TITLE
InputFilter not used for filtering `POST` data

### ISSUE THREAD

**Issue by Wilt** [zfcampus/zf-apigility-skeleton#75]
Hello,

I have a question or an issue, but I am not sure which of the two it is since I don't know if the behavior is wrong or expected. Let me explain.

When I register an inputFilter for a certain entity and patch an entity with data (a field) that is not registered in the inputFilter I get an `ApiProblem` response with status 400 and a message "Unrecognized field name".

Now in another case I post data for creating a new entity and I include the same invalid field in the data. When I look at the `$data` object in the create method in my `ResourceListener` the `$data` is apparently not filtered by the inputFilter, because unknown data is still present in the `$data` object. Normally I would expect the inputFilter to take care of unknown/unwanted by filtering it. Something like this:

```
$inputFilter->setData($unfilteredData);
if(!$inputFilter->isValid()){
    ...throw exception or return ApiProblem
}
$filteredData = $inputFilter->getValues();
```

Is the module (as the name would suggest) only for validation of data and that is why the registered inputFilters are not used for filtering `POST` data at all? Does it mean I still manually have to pull the data trough the filter in my ResourceListener.
I also looked at the `zfcampus/zf-content-validation` src files but could not find anything related to actually filtering the data.

Thanks.

**Comment by jbenoit2011** [comment]
@weierophinney Is this issue still existing ? If yes, I could suggest a PR to add the flag.

**Comment by Zbintiosul** [comment]
Until now exist a global option like:  'filter_resource_listeners_data_for_all_methods' => true, to be by default filtered data not raw data? To know.

**Comment by Wilt** [comment]
When using `pre` and `post` event listeners and resolving the `data` from the param from the event it turns out the data array also holds the unfiltered data (raw post data). 

I think it is a design mistakes inside the `Apigility`/`zf-rest` architecture to pass raw unfiltered data to the `RestController` classes, the `ResourceListener` and `post` and `pre` controller events. I don't think people expect raw post values in this stage of their application process (after dispatch). I strongly believe mistakes are bound to happen. 
I know that filtered values can be resolved indirectly from the event like this:

        $restController = $event->getTarget();
        $resource = $restController->getResource();
        $inputFilter = $resource->getInputFilter();
        $data = $inputFilter->getValues();

But I would strongly suggest passing filtered data to the controller class methods and the `pre` and `post` events in the `RestController`. It would surely be much more intuitive.

**Comment by Wilt** [comment]
For those ending up here there are two flags that can be used for setting this up according to the documentation here: https://apigility.org/documentation/modules/zf-content-validation#user-configuration:

- `use_raw_data`: if NOT present, raw data is ALWAYS injected into the "BodyParams" container (defined by zf-content-negotiation). If this key is present and a boolean false, then the validated, filtered data from the input filter will be used instead.

- `allows_only_fields_in_filter`: if present, and `use_raw_data` is boolean false, the value of this flag will define whether or not additional fields present in the payload will be merged with the filtered data.
