### ISSUE TITLE
I build an Rest API that include a property type is photo, so how can I get the photo when POST a new entity?.

### ISSUE THREAD

**Issue by ngldchm** [zfcampus/zf-apigility-skeleton#78]
![screen shot 2014-11-20 at 5 32 00 pm](https://cloud.githubusercontent.com/assets/541442/5123164/4feec5ba-70db-11e4-9488-a733a4e37417.png)
![screen shot 2014-11-20 at 5 32 33 pm](https://cloud.githubusercontent.com/assets/541442/5123165/4ff438ec-70db-11e4-8006-e12526afc814.png)

I have an Event table in Database, each event have a thumb image so I have to post Photo from API create new event.

I have follow with the https://apigility.org/documentation/recipes/upload-files-to-api
To step Validators then this step In a REST service, use this:  $inputFilter = $this->getInputFilter();
I don't know how to do this. I can not find any generated source code of API web service except XXX\V1\Rest\Event2\Event2Collection.php
and XXX\V1\Rest\Event2\Event2Entity.php

But How can I make it works?

I have more questions:
1. What is the right solution to post an entity include Photo? And how to manager Photo at server side?
2. How can I custom the API that generate by Apigility? Where are the generated source files?

Sorry because I have just a beginner in PHP and Apigility.

**Comment by Zbintiosul** [comment]
For upload photo did a RPC service

**Comment by jguittard** [comment]
almost 2 years old, closing
