### ISSUE TITLE
Version 1.10 contains config that breaks apigility

### ISSUE THREAD

**Issue by addersuk** [zfcampus/zf-apigility-skeleton#86]
Hi, I'm just trying the easy setup of apigility but i've encountered an error. 

The following process is repeatable:
1.  curl -sS https://apigility.org/install | php
2. cd apigility
3. php public/index.php development disable

The site then encounters a error when accessing.

PHP Warning:  require_once(/home/matthew/tmp/zf-apigility-skeleton-1.1.0/module/Application/Module.php): failed to open stream: No such file or directory in /home/api-findstuffcheaper/temp/apigility/vendor/zendframework/zendframework/library/Zend/Loader/ModuleAutoloader.php on line 147
PHP Fatal error:  require_once(): Failed opening required '/home/matthew/tmp/zf-apigility-skeleton-1.1.0/module/Application/Module.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/api-findstuffcheaper/temp/apigility/vendor/zendframework/zendframework/library/Zend/Loader/ModuleAutoloader.php on line 147

The problem seems to stem from data/cache/module-config-cache.application.config.cache.php that contains a number of full paths that are incorrect, ie:
'/home/matthew/tmp/zf-apigility-skeleton-1.1.0/module/Application/config/../view/layout/layout.phtml'
'/home/matthew/tmp/zf-apigility-skeleton-1.1.0/module/Application/config/../view/application/index/index.phtml'
'/home/matthew/tmp/zf-apigility-skeleton-1.1.0/module/Application/config/../view/error/404.phtml'
 '/home/matthew/tmp/zf-apigility-skeleton-1.1.0/module/Application/config/../view/error/index.phtml'
'/home/matthew/tmp/zf-apigility-skeleton-1.1.0/vendor/zfcampus/zf-oauth2/config/../view/zf/auth/authorize.phtml'
'/home/matthew/tmp/zf-apigility-skeleton-1.1.0/vendor/zfcampus/zf-oauth2/config/../view/zf/auth/receive-code.phtml'
'/home/matthew/tmp/zf-apigility-skeleton-1.1.0/module/Application/config/../view'
'/home/matthew/tmp/zf-apigility-skeleton-1.1.0/vendor/zfcampus/zf-apigility-documentation/config/../view'
'/home/matthew/tmp/zf-apigility-skeleton-1.1.0/vendor/zfcampus/zf-oauth2/config/../view'

I've had a look at this repository, but can't find where that config is coming from.

Adam

**Comment by ezimuel** [comment]
@addersuk It seems we shipped a data/cache folder  in the installer with some local files, we will remove it. In the meantime you can just delete these cache files using the command:
```
rm data/cache/*.php
```
Thanks for reporting this issue.

**Comment by addersuk** [comment]
Its all working now. Thanks for quick response and creating a great api framework.

**Comment by weierophinney** [comment]
I've fixed the packages to remove those cache files; thanks for the report!

**Comment by ajzele** [comment]
FYI, this just happened to me on v1.3.3.
