### ISSUE TITLE
Development mode failure in production

### ISSUE THREAD

**Issue by kevinpapst** [zfcampus/zf-apigility-skeleton#94]
Hi!

I recently updated to newest Apigility version and merged some changes from the skeleton app as well, when I stumble upon this problem:

You always load ZF\DevelopmentMode in:
https://github.com/zfcampus/zf-apigility-skeleton/blob/master/config/application.config.php#L11

But only require it in dev:
https://github.com/zfcampus/zf-apigility-skeleton/blob/master/composer.json#L39
First time you might catch this error is on any non-development environment.

I assume moving zf-development-mode to the "require" is the approach to fix this, correct? If so, I can sent in a pull request.

Thanks 
Kevin

**Comment by ezimuel** [comment]
@kevinpapst we solved this in PR https://github.com/zfcampus/zf-apigility-skeleton/pull/92 in develop branch. We'll merge it in master soon, with the new Apigility version 1.1.2.

**Comment by kevinpapst** [comment]
Oh, ok. Could have looked there, but forgot ;-)  Thanks for your feedback!
