### ISSUE TITLE
New API fails:  Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by texdc** [zfcampus/zf-apigility-skeleton#95]
I installed with:
```
$ composer create-project -sdev zfcampus/zf-apigility-skeleton . 1.1.1
$ php public/index.php development enable
```
I then loaded up the admin page in my browser and clicked 'New API'.  The modal popped-up and I entered a name and clicked 'Create'.  A success 'API was created' message showed, but nothing else happened.  The console shows a javascript error in a `resolve` handler:

![screen shot 2015-07-02 at 4 41 10 pm](https://cloud.githubusercontent.com/assets/1590605/8488670/039db482-20da-11e5-8909-8a2a5497cdb7.png)

**Comment by weierophinney** [comment]
I cannot reproduce locally following the same steps. :-/

**Comment by texdc** [comment]
Ok, it was a file permissions issue.  I see the note in the 'Getting Started' docs, but I never saw a warning dialog.
